.\" .TH SELAM 1 "19 Subat 2026" "1.0" "Selam Komutu Klavuzu"
.\" .SH NAME
.\" ps_test \- push swap test script.
.\" .SH SYNOPSIS
.\" "Usage: $0 <run|test> [--strategy STRATEGY|-s STRATEGY|--strategy=STRATEGY] [-x N] [-n N]  <make_target> [preset|numbers...]"

.\" .B ps_test
.\" <run|test> [(
.\" -s
.\" .I STRATEGY
.\" | --strategy[<=
.\" .I STRATEGY
.\" >])
.\" ] 
.\" [-x
.\" .I N]
.\" [-n
.\" .I N] 
.\" <
.\" .I make_target>
.\" [
.\" .I preset
.\" |numbers...] [\-v] [\-n
.\" .I isim]
.\" .SH DESCRIPTION
.\" .B ps_test
.\" komutu, push swap test script'i çalıştırır.
.\" .SH OPTIONS
.\" .IP -v
.\" Versiyon bilgisini gösterir.
.\" .IP "-n isim"
.\" Belirtilen isme selam verir.
.\" .IP "-s, --strategy [strategy]"
.\" default strategy is simple if it is not given.
.\" .IP "-x N"
.\" kac kere execute edilecegi.

.\" .SH YAZAR
.\" AI & murmurlab

.\" $0  <command> [args]

.\" $0 test	[(--strategy | -s) [__STRATEGY__]] [-x N] [-n N] <make_target>
.\" [preset|numbers...]

.TH PS_TEST 1 "19 Subat 2026" "1.0" "Push Swap Test Script Kilavuzu"
.SH NAME
ps_test \- Push_swap projesi icin otomatik test betigi.
.SH SYNOPSIS
.B ps_test
.B run|test
[
.B \-x
.I N
]
[
.B \-n
.I N
]
.I make_target
[
.B \-s
.I STRATEGY
]
[
.I preset
|
.I numbers...
]
.SH DESCRIPTION
.B ps_test
komutu, push_swap projesinin dogrulugunu ve verimliligini test etmek icin kullanilir. 
Farkli sayi dizilimleri ve stratejilerle testler kosturur.
.SH OPTIONS
.TP
.BR \-s ", " \-\-strategy " [" \fISTRATEGY\fP ]
Kullanilacak stratejiyi belirler. Deger verilmezse 'simple' varsayilir.
.TP
.BI \-x " N"
Testin kac kez tekrar edilecegini (execution count) belirtir.
.TP
.BI \-n " N"
Test edilecek sayi adedini belirler.
.TP
.B \-v
Versiyon bilgisini gosterir.
.SH EXAMPLES
.B ps_test test -s random -x 100 500
.br
500 sayi ile 'random' stratejisini kullanarak 100 kez test eder.
.SH AUTHOR
AI & murmurlab
